### ISSUE TITLE
Public Trello Board?

### ISSUE THREAD

**Issue by jsmith-dev** [ethereumproject/volunteer#14]
Threaded GitHub comments reaching capacity of clarity threshold. Any chance a Trello board?

**Comment by whatisgravity** [comment]
@colibry545 Started one in the last 24 hours, I believe they are organizing the use of it.

**Comment by colibry545** [comment]
@jsmith-dev There is a private Trello board for Core Development currently. I can create a new one for different projects and teams. Please let me know if you need a board for your project and I can set it up. 
Or if you want to see the public board with overall status and work in progress, available for everyone, I think I can do that too. 
So please let me know what do you mean

**Comment by whatisgravity** [comment]
Is there a way to make it read only to the public? 

Jsmith-dev is apart of the organization currently but not a public member. People are still trying to find out where they can contribute time so a publicly viewable board would allow us to be transparent and make it easier to see what needs to be done.

**Comment by colibry545** [comment]
@whatisgravity Yes It is possible to make existing board’s public view. Please confirm and I’ll make it public.

**Comment by whatisgravity** [comment]
Yeah, I think its much better for it to be public, we should strive for maximum transparency. It makes it a lot easier for the organization to get volunteers if it is very clear what tasks need to be completed. 

Write access can be granted after a established track record of activity. 

It may also be beneficial to add information about the Trello board in the README. The explorer project @elaineo is working on may already warrant its own board, you may want to reach out and see if you can provide help to that project since the number of members is growing rapidly.

**Comment by jsmith-dev** [comment]
@colibry545 & all

Broadly my meaning was public - as in - for all to see...

**Comment by whatisgravity** [comment]
It should be public soon, I agree it will be much more useful than a github issue thread that is growing very large. That thread is very useful for helping orient new volunteers but we still need an easy way for volunteers to quickly find tasks they can immediately work on.

**Comment by colibry545** [comment]
done https://trello.com/b/aiSzWBm7/core-etc-development

**Comment by whatisgravity** [comment]
@colibry545 Thank you for taking care of that quickly, if you have time can you please add it to the projects section of the README of this repository and give some explanation to volunteers who may not be familiar with Trello

**Comment by colibry545** [comment]
@whatisgravity sure, will do it
