### ISSUE TITLE
Consolidate a few Slack channels

### ISSUE THREAD

**Issue by igetgames** [ethereumproject/volunteer#39]
Slack is a great medium for us to get together and communicate, but sometimes it becomes difficult to find the right channel for discussion. Some channels discuss the same topic, but were created with similar intentions earlier in the project. We also have a bot that bridges channels across two IRC networks, and due to where it's currently situated, those channels might be excluded from pertinent conversations. Here's what I propose:

- Move the IRC bridge out of #irc into #general and archive #irc.
- Move the IRC bridge out of #global_planning into #classic, and archive #global_planning.

Note that there are 69 members of #global_planning, and 157 in #classic, and nearly all members overlap. Since I maintain the IRC bridge bot, I can move it once we decide to archive those channels.

**Comment by arvicco** [comment]
I support consolidation of #irc and #general. My concern about providing IRC bridge to #classic is that it is an access-controlled channel. Admins only invite ETC supporters to it, not just everyone. Since anyone can join the corresponding irc room, it kind of defies the purpose. Unless we create some kind of "secret" IRC room with access only to ETC supporters who don't want to be on Slack for some reason - such as @whatisgravity.

In my opinion, #global_planning serves no useful purpose and just confuses everyone. Also, I see #random as unneeded distraction. If we could consolidate an all open discussion in #general, and ETC-supporters discussion (access-restricted) in #classic, it would be a win for everyone, and communication will improve, IMHO. Of course, any specialized/team discussion will still happen in specialized channels, but we need some common community-wide channels to communicate. Let it be #general/#classic on Slack.

**Comment by igetgames** [comment]
@arvicco Thank you for the feedback. The private global_planning channel is already bridged to the corresponding room that @whatisgravity resides in, on OFTB.net. There are only two other developers in that room currently, not including the bridge bot. So moving the bridge to the private classic channel would just expose gravity, @ericsomdahl (who is already on Slack) and one more developer to the larger classic community. AFAICT everyone in global_planning is already in classic, so once @whatisgravity is in classic, global_planning becomes redundant. Let me know what you think.

The second IRC bridge links #irc to the #ethereumclassic channel freenode.net. I think moving that bridge to #general would be a great way to encourage more discussion between Slack and IRC. I can go ahead and make that switch if no one has any objections.

BTW, I'm not familiar at all with Telegram but if it makes sense to incorporate that into Slack, let me know so that I can look into it.

Do we have any projects that are currently using Gitter?

**Comment by arvicco** [comment]
Looks like a good plan then, no objections to consolidation. I'm not familiar with Telegram either, but if there is a way to make a bridge between ETC channel on Telegram and #general on Slack, that would be swell.

**Comment by sethfork** [comment]
> - Move the IRC bridge out of #irc into #general and archive #irc.
- Move the IRC bridge out of #global_planning into #classic, and archive #global_planning.

These changes appear to be no-brainers. I support @igetgames moving ahead with this.

-
Regarding the further consolidation of slack channels:

A small team focussed on community development has been forming. We're quite active in our discussions on community management related topics such as channel maintenance.

In the interest of efficiency and specialization; I propose we close this issue and delegate the further consolidation of channels to our team: @ChuckSRQ, @CarloVetc, @eragmus, @arvicco, and myself.

**Comment by igetgames** [comment]
Sounds good to me. Thanks guys!
